#!/usr/bin/env python3
"""
Extract every idea from the v1 feature list that was NEVER BUILT, and show
which spec now owns it.

These are the ones genuinely at risk of being lost: there is no code to remind
anyone they existed, only the words in the doc.

  planned, not built      parked        idea inbox        half-built
Run:  python3 scripts/build-idea-ledger.py > docs/IDEA-LEDGER.md
"""
import re, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MARKS = {'⬜': 'planned, never built', '⏭': 'parked',
         '\U0001f4a1': 'idea inbox', '\U0001f504': 'half-built'}

# v1 section number -> owning spec, from specs/ROADMAP.md coverage matrix.
OWNER = [
 (r'^1\.[1-3]', '005-office-setup-roster'), (r'^1\.[4-5]', '005-office-setup-roster'),
 (r'^1\.6', '013-home-dashboard'), (r'^1\.7', '011-connections-vault'),
 (r'^2\.1$', '011-connections-vault'), (r'^2\.2', '008-approvals-money-gate'),
 (r'^2\.3', '008-approvals-money-gate'), (r'^2\.4', '011-connections-vault'),
 (r'^2\.5', '009-memory-system'), (r'^2\.6', '010-rulebook-police'),
 (r'^2\.7', '001-hermes-runtime-contract'), (r'^2\.8', '018-telegram-phone'),
 (r'^2\.9', '001-hermes-runtime-contract'), (r'^2\.10', '001-hermes-runtime-contract'),
 (r'^2\.11', '011-connections-vault'), (r'^2\.12', '004-front-door-accounts'),
 (r'^2\.13', '003-app-shell'),
 (r'^3\.0', '003-app-shell'), (r'^3\.1$', '003-app-shell'), (r'^3\.2$', '004-front-door-accounts'),
 (r'^3\.3', '005-office-setup-roster'), (r'^3\.4', '013-home-dashboard'),
 (r'^3\.[5-8]', '007-missions-board'), (r'^3\.9', '015-office-3d'),
 (r'^3\.10', '014-council-assembly'), (r'^3\.11', '008-approvals-money-gate'),
 (r'^3\.12', '009-memory-system'), (r'^3\.13', '010-rulebook-police'),
 (r'^3\.14', '011-connections-vault'), (r'^3\.15', '012-cost-ledger'),
 (r'^3\.1[6-7]', '019-docs-files'), (r'^3\.1[8-9]', '013-home-dashboard'),
 (r'^3\.20', '016-dev-room'), (r'^3\.21', '003-app-shell'),
 (r'^3\.22', '005-office-setup-roster'), (r'^3\.23', '013-home-dashboard'),
 (r'^4\.', '015-office-3d'), (r'^5\.', '006-maria-ai-layer'),
 (r'^6\.', '002-pc-bridge'), (r'^7', '017-home-base'),
 (r'^8\.', '011-connections-vault'), (r'^9', '016-dev-room'),
 (r'^10', '018-telegram-phone'), (r'^11', '009-memory-system'),
 (r'^12\.1', '004-front-door-accounts'), (r'^12\.2', '003-app-shell'),
 (r'^12\.4', '002-pc-bridge'), (r'^12\.', 'each feature owns its own'), (r'^13', '020-proof-system'),
 (r'^14\.', 'spread across all twenty'), (r'^15', 'the constitution'),
 (r'^16', 'history (orientation only)'),
]

def owner_for(sec):
    for pat, who in OWNER:
        if re.match(pat, sec):
            return who
    return '(unmapped)'

def main():
    src = open(os.path.join(ROOT, 'docs/FEATURES-V1-ORIGINAL.md')).read().split('\n')
    section, title, rows = '0', 'What this is', []
    for n, line in enumerate(src, start=1):
        if n <= 16:
            continue   # the doc's own status-mark legend, not a feature
        h = re.match(r'^#{2,4}\s+([\d.]+)\s+(.*)', line)
        if h:
            section, title = h.group(1).rstrip('.'), h.group(2)
            continue
        found = [MARKS[m] for m in MARKS if m in line]
        if found and line.strip():
            rows.append((section, title, sorted(set(found)), line.strip()))

    by_owner = {}
    for sec, title, kinds, text in rows:
        by_owner.setdefault(owner_for(sec), []).append((sec, title, kinds, text))

    out = []
    W = out.append
    W("# The idea ledger — every unbuilt idea, and where it went\n")
    W("> **This file answers one question: how do I know I am not losing my ideas?**\n>")
    W("> `docs/FEATURES.md` keeps every *word* of your original list — "
      "`scripts/verify-nothing-lost.py` proves that mechanically.")
    W("> But words surviving is not the same as ideas being carried forward. The riskiest")
    W("> items are the ones that were **never built**: there is no code to remind anyone")
    W("> they existed, only a line in a document.\n>")
    W("> So this file pulls every one of them out and names the spec now responsible for it.")
    W("> Generated by `scripts/build-idea-ledger.py` — re-run it any time.\n")
    W(f"**{len(rows)} unbuilt or partly-built items** found across "
      f"{len(set(r[0] for r in rows))} sections of your original list.\n")
    W("| Mark | Meaning | Count |")
    W("|---|---|---|")
    for m, meaning in MARKS.items():
        c = sum(1 for r in rows if meaning in r[2])
        W(f"| {m} | {meaning} | {c} |")
    W("\n---\n")

    for who in sorted(by_owner, key=lambda k: (k.startswith('('), k)):
        items = by_owner[who]
        W(f"## → `{who}`  ({len(items)} item{'s' if len(items)!=1 else ''})\n")
        last = None
        for sec, title, kinds, text in items:
            if sec != last:
                W(f"\n**v1 §{sec} — {title}**\n")
                last = sec
            W(f"- {text}")
        W("")
    W("\n---\n")
    W("## How to use this\n")
    W("When a spec is planned, check this ledger for its section. Every item listed")
    W("against it must appear in that feature's `plan.md` — either scheduled, or")
    W("explicitly deferred with a reason. **An item may be moved later. It may not")
    W("quietly disappear.**\n")
    W("If something here has no home, or is in the wrong one, say so and it gets fixed.")
    print('\n'.join(out))

if __name__ == '__main__':
    main()
